-- MySQL Script generated by MySQL Workbench
-- 04/16/17 02:32:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema invest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema invest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `invest` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `invest` ;

-- -----------------------------------------------------
-- Table `invest`.`tipoProductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`tipoProductos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre_producto` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad_producto` INT NOT NULL COMMENT '',
  `costo` DECIMAL(15,2) NOT NULL COMMENT '',
  `tipoProductos_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_productos_tipoProductos_idx` (`tipoProductos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_productos_tipoProductos`
    FOREIGN KEY (`tipoProductos_id`)
    REFERENCES `invest`.`tipoProductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`valoresAgregados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`valoresAgregados` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`tipoIdentificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`tipoIdentificacion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `num_identificacion` VARCHAR(45) NOT NULL COMMENT '',
  `tipoIdentificacion_id` INT NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_clientes_tipoIdentificacion1_idx` (`tipoIdentificacion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_clientes_tipoIdentificacion1`
    FOREIGN KEY (`tipoIdentificacion_id`)
    REFERENCES `invest`.`tipoIdentificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`empleados` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido` VARCHAR(45) NOT NULL COMMENT '',
  `identificacion` VARCHAR(45) NOT NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NOT NULL COMMENT '',
  `tipoIdentificacion_id` INT NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_empleados_tipoIdentificacion1_idx` (`tipoIdentificacion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_empleados_tipoIdentificacion1`
    FOREIGN KEY (`tipoIdentificacion_id`)
    REFERENCES `invest`.`tipoIdentificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `clientes_id` INT NOT NULL COMMENT '',
  `empleados_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ventas_clientes1_idx` (`clientes_id` ASC)  COMMENT '',
  INDEX `fk_ventas_empleados1_idx` (`empleados_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `invest`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `invest`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`productosVentasDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`productosVentasDetalle` (
  `id` VARCHAR(10) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio` DECIMAL(15,2) NOT NULL COMMENT '',
  `productos_id` INT NOT NULL COMMENT '',
  `valoresAgregados_id` INT NOT NULL COMMENT '',
  `ventas_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_productosVentasDetalle_productos1_idx` (`productos_id` ASC)  COMMENT '',
  INDEX `fk_productosVentasDetalle_valoresAgregados1_idx` (`valoresAgregados_id` ASC)  COMMENT '',
  INDEX `fk_productosVentasDetalle_ventas1_idx` (`ventas_id` ASC)  COMMENT '',
  CONSTRAINT `fk_productosVentasDetalle_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `invest`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productosVentasDetalle_valoresAgregados1`
    FOREIGN KEY (`valoresAgregados_id`)
    REFERENCES `invest`.`valoresAgregados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productosVentasDetalle_ventas1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `invest`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rif` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `user_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `proveedores_id` INT NOT NULL COMMENT '',
  `empleados_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_compras_proveedores1_idx` (`proveedores_id` ASC)  COMMENT '',
  INDEX `fk_compras_empleados1_idx` (`empleados_id` ASC)  COMMENT '',
  CONSTRAINT `fk_compras_proveedores1`
    FOREIGN KEY (`proveedores_id`)
    REFERENCES `invest`.`proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_empleados1`
    FOREIGN KEY (`empleados_id`)
    REFERENCES `invest`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invest`.`productosComprasDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invest`.`productosComprasDetalle` (
  `id` VARCHAR(10) NOT NULL COMMENT '',
  `fecha` DATE NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  `precio` DECIMAL(15,2) NOT NULL COMMENT '',
  `compras_id` INT NOT NULL COMMENT '',
  `productos_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_productosComprasDetalle_compras1_idx` (`compras_id` ASC)  COMMENT '',
  INDEX `fk_productosComprasDetalle_productos1_idx` (`productos_id` ASC)  COMMENT '',
  CONSTRAINT `fk_productosComprasDetalle_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `invest`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productosComprasDetalle_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `invest`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
